//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archivo
    {
        public int id_archivo { get; set; }
        public string nombreArchivo { get; set; }
        public string baseArchivo { get; set; }
        public Nullable<int> id_HistorialRespuesta { get; set; }
        public string nombreFalso { get; set; }
    
        public virtual HistorialRespuesta HistorialRespuesta { get; set; }
    }
}
