//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConCopiaRespuesta
    {
        public int id_ConCopiaRespuesta { get; set; }
        public string correo { get; set; }
        public Nullable<bool> borrado { get; set; }
        public Nullable<int> Fk_HistorialRespuesta { get; set; }
    
        public virtual HistorialRespuesta HistorialRespuesta { get; set; }
    }
}
