//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialRespuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistorialRespuesta()
        {
            this.Archivo = new HashSet<Archivo>();
            this.ConCopiaRespuesta = new HashSet<ConCopiaRespuesta>();
        }
    
        public int id_HistorialRespuesta { get; set; }
        public string Respuesta { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public Nullable<int> bPrivado { get; set; }
        public Nullable<int> id_Ticket { get; set; }
        public Nullable<int> id_EstadoTicket { get; set; }
        public Nullable<int> id_Usuarios { get; set; }
        public Nullable<bool> RespuestaCerrado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Archivo> Archivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConCopiaRespuesta> ConCopiaRespuesta { get; set; }
        public virtual EstadoTicket EstadoTicket { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
