//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HorasTicket
    {
        public int idHoras { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string horas { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> FK_idTicket { get; set; }
        public Nullable<System.DateTime> fechaTermino { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
