//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloPortal4Entities : DbContext
    {
        public ModeloPortal4Entities()
            : base("name=ModeloPortal4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ambiente> Ambiente { get; set; }
        public virtual DbSet<Archivo> Archivo { get; set; }
        public virtual DbSet<ArchivosTicket> ArchivosTicket { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<BaseDeDatos> BaseDeDatos { get; set; }
        public virtual DbSet<CatIndicente> CatIndicente { get; set; }
        public virtual DbSet<ConCopia> ConCopia { get; set; }
        public virtual DbSet<ConCopiaRespuesta> ConCopiaRespuesta { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EstadoTicket> EstadoTicket { get; set; }
        public virtual DbSet<FotoPerfil> FotoPerfil { get; set; }
        public virtual DbSet<HistorialRespuesta> HistorialRespuesta { get; set; }
        public virtual DbSet<HorasTicket> HorasTicket { get; set; }
        public virtual DbSet<Logo> Logo { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Prioridad> Prioridad { get; set; }
        public virtual DbSet<ProdEmpresa> ProdEmpresa { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProdUsuario> ProdUsuario { get; set; }
        public virtual DbSet<ProdxContrato> ProdxContrato { get; set; }
        public virtual DbSet<ProdxProy> ProdxProy { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<ResponsableTicket> ResponsableTicket { get; set; }
        public virtual DbSet<RubroEmpresa> RubroEmpresa { get; set; }
        public virtual DbSet<SistemaOperativo> SistemaOperativo { get; set; }
        public virtual DbSet<SLA> SLA { get; set; }
        public virtual DbSet<SubCatIndicente> SubCatIndicente { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<TicketVersionAfectada> TicketVersionAfectada { get; set; }
        public virtual DbSet<TipoSoporte> TipoSoporte { get; set; }
        public virtual DbSet<TipoTicket> TipoTicket { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<VersionProducto> VersionProducto { get; set; }
        public virtual DbSet<VersionProyecto> VersionProyecto { get; set; }
    }
}
