//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdEmpresa
    {
        public int id_ProdEmpresa { get; set; }
        public string VersionExacta { get; set; }
        public Nullable<int> bActivo { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public Nullable<int> id_BD { get; set; }
        public Nullable<int> id_SO { get; set; }
    
        public virtual BaseDeDatos BaseDeDatos { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual SistemaOperativo SistemaOperativo { get; set; }
    }
}
