//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdxContrato
    {
        public int id_ContratoeEmpProd { get; set; }
        public Nullable<int> id_Contrato { get; set; }
        public Nullable<int> id_Producto { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
