//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SLA()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int idp_SLA { get; set; }
        public string nomSLA { get; set; }
        public Nullable<int> nroHrsSLA { get; set; }
        public Nullable<int> idAmbiente { get; set; }
        public Nullable<int> id_Prioridad { get; set; }
    
        public virtual Ambiente Ambiente { get; set; }
        public virtual Prioridad Prioridad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
