//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.ArchivosTicket = new HashSet<ArchivosTicket>();
            this.ConCopia = new HashSet<ConCopia>();
            this.HistorialRespuesta = new HashSet<HistorialRespuesta>();
            this.HorasTicket = new HashSet<HorasTicket>();
            this.TicketVersionAfectada = new HashSet<TicketVersionAfectada>();
        }
    
        public int id_Ticket { get; set; }
        public string Asunto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> AdjuntosEvidencia { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public Nullable<int> UsuarioResolucion { get; set; }
        public Nullable<int> id_Proyectos { get; set; }
        public Nullable<int> id_SubCatIncidente { get; set; }
        public Nullable<int> id_Area { get; set; }
        public Nullable<int> id_Usuarios { get; set; }
        public Nullable<int> id_TipoSoporte { get; set; }
        public Nullable<int> id_EstadoTicket { get; set; }
        public Nullable<int> id_tipoTicket { get; set; }
        public Nullable<int> id_Prioridad { get; set; }
        public Nullable<int> idp_SLA { get; set; }
        public Nullable<System.DateTime> FechaEstimadaResolucion { get; set; }
        public Nullable<int> Eliminado { get; set; }
        public Nullable<System.DateTime> UltimaRespuesta { get; set; }
        public string idTicketPortalEmpresa { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public Nullable<bool> Visto { get; set; }
        public Nullable<bool> VistoCliente { get; set; }
        public string PorHacer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivosTicket> ArchivosTicket { get; set; }
        public virtual Area Area { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConCopia> ConCopia { get; set; }
        public virtual EstadoTicket EstadoTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialRespuesta> HistorialRespuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorasTicket> HorasTicket { get; set; }
        public virtual Prioridad Prioridad { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual SLA SLA { get; set; }
        public virtual SubCatIndicente SubCatIndicente { get; set; }
        public virtual TipoSoporte TipoSoporte { get; set; }
        public virtual TipoTicket TipoTicket { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketVersionAfectada> TicketVersionAfectada { get; set; }
    }
}
