//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketVersionAfectada
    {
        public int id_TicketVersion { get; set; }
        public Nullable<int> id_Ticket { get; set; }
        public Nullable<int> id_VersionProyecto { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual VersionProyecto VersionProyecto { get; set; }
    }
}
